### ISSUE TITLE
Symfony\Component\VarDumper\Caster\DateCaster not found

### ISSUE THREAD

**Issue by mauryaratan** [spatie/wordpress-ray#24] opened 2021-01-16 08:35 UTC
Hey there! Loving the Ray so far 😍 

Was trying to print an object and came across this error.

Fatal error: Uncaught Error: Class 'Symfony\Component\VarDumper\Caster\DateCaster' not found
in /public_html/content/plugins/spatie-ray/vendor/symfony/var-dumper/Cloner/AbstractCloner.php on line 348

Using the WordPress plugin btw.

**Comment by jeffreyvr** [comment] 2021-01-16 13:50
Just did a quick check and can reproduce the error. Happens when for example running:

```php
ray(new DateTime);
```

Appears to be caused by the missing namespace prefixes on the `$defaultCasters` array within `AbstractCloner.php` from line 25.

**Comment by jeffreyvr** [comment] 2021-01-16 15:08
@freekmurze I guess the imposter-plugin package does not pickup on namespaces within arrays etc.

This following might not be an ideal solution, but a quick fix could be running a find replace on the file after the composer install script.

```json
"post-install-cmd": [
    "sed -i '' 's/'\\''Symfony/'\\''Spatie\\\\WordPressRay\\\\Symfony/g' ./vendor/symfony/var-dumper/Cloner/AbstractCloner.php"
]
```

**Comment by freekmurze** [comment] 2021-01-16 19:37
@jeffreyvr thanks for checking. I think that PR might be the way to go for now. Could you PR that?

**Comment by freekmurze** [comment] 2021-01-17 12:04
Will be fixed by #25

**Closed by freekmurze** 2021-01-17 12:04 UTC

**Comment by stanwarri** [comment] 2021-01-18 21:38
I'm still experiencing this error even after upgrading to the latest wordpress version

**Comment by freekmurze** [comment] 2021-01-19 16:49
I'll retry by tagging a new version later tonight!

**Comment by freekmurze** [comment] 2021-01-19 19:52
I've tagged a new version. The modified classnames are now written correctly: https://github.com/spatie/wordpress-ray/blob/855a811487751a3e96c30ab1f2c57a7ef4f3d6f0/vendor/symfony/var-dumper/Cloner/AbstractCloner.php#L24
